FROM pytorch/pytorch:latest as python-base

# Set the working directory in the container
WORKDIR /app

COPY pyproject.toml poetry.lock ./

# Install Poetry
RUN pip install poetry
RUN poetry config virtualenvs.create false

RUN poetry lock
# Install dependencies
RUN poetry install --no-root --no-interaction --no-ansi
# Copy the entire project code to the container
COPY . .

# Command to run your application with the "inference" argument
# Add another command line argument if you want to include a document collection.
CMD ["python", "nlp_final_project/main.py", "inference"]
